services:
  fincthub-api:
    image: suistwn/fincthub-api:latest
    container_name: fincthub-api
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - apps-network

  fincthub-ui:
    image: suistwn/fincthub-ui:latest
    container_name: fincthub-ui
    restart: always
    ports:
      - "3000:3000"
    networks:
      - apps-network

networks:
  apps-network:
    external: true
